<a href="https://colab.research.google.com/github/soumiyavenkatesan/DatascienceTask/blob/main/Task4s.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
import numpy as np
z=np.zeros((10,10))
print("%d bytes"%(z.size*z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
%run 'python -c"import numpy; numpy.info(numpy.add)"'

Exception: ignored

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
import numpy as np
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
import numpy as np
z=np.arange(50)
z=z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
import numpy as np
z=np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
import numpy as np
z=np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
import numpy as np
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
import numpy as np
z=np.random.random((3,3,3))
print(z)

[[[0.03881053 0.76944093 0.97989505]
  [0.55461257 0.47208653 0.64859398]
  [0.49163219 0.17572    0.94075995]]

 [[0.81846252 0.4789334  0.55609268]
  [0.27015851 0.47736911 0.25241633]
  [0.60538169 0.44854329 0.03601366]]

 [[0.28397652 0.323419   0.63427015]
  [0.58345321 0.01555757 0.03828708]
  [0.21579276 0.49725462 0.64721299]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
import numpy as np
z=np.random.random((10,10))
zmin,zmax=z.min(),z.max()
print(zmin,zmax)

0.0008607043893474886 0.9995753689910839


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
import numpy as np
z=np.random.random(30)
m=z.mean()
print(m)

0.5310386186432285


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np
z=np.ones((5,5))
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:

import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
import numpy as np
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
import numpy as np
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:

import numpy as np
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
import numpy as np
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.50904384 0.74587814 0.99816243 0.20402213 0.91578391]
 [0.21571892 1.         0.84374518 0.72544121 0.53548051]
 [0.81309243 0.         0.58924494 0.06381364 0.80881562]
 [0.56057212 0.33088141 0.30374726 0.1807634  0.05890957]
 [0.34345727 0.69601788 0.5445526  0.81658159 0.46353001]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-3-c3ff0fe4fc5b>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-8-779629cb3f15>:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-8-779629cb3f15>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
import numpy as np
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 10. -10.   7. -10.   7.   7. -10.   3.  10.   1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 4 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import numpy as np
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-12-62fa731a8227>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[8. 7. 4. 8. 1. 4. 4. 8. 5. 4.]
[8. 7. 4. 8. 1. 4. 4. 8. 5. 4.]
[8. 7. 4. 8. 1. 4. 4. 8. 5. 4.]
[8 7 4 8 1 4 4 8 5 4]
[8. 7. 4. 8. 1. 4. 4. 8. 5. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.04412544 0.07609409 0.07879208 0.2158771  0.26824419 0.2790449
 0.32373012 0.41327087 0.75513929 0.77345379]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.95914642 0.51026777 0.74977875 0.24890544 0.55883308 0.3167022
 0.88160433 0.48722196 1.03277562 0.08428148]
[1.14901336 1.23081935 0.78039772 1.1729909  1.38763664 0.71778134
 1.53154745 0.49627681 0.38653493 0.56336107]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.58005798 0.         0.04262683 0.06753929 0.21994981 0.21488836
 0.10241777 0.35614084 0.67474215 0.65559196]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

63


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-21-6f1aa4d7a2ff>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.30681223 0.28519562 0.59342101 1.18873526 0.72166297
  0.49033107 1.13566133 0.6869617  0.83296278]
 [0.30681223 0.         0.35588211 0.7073221  1.02351632 0.82106444
  0.3102678  0.97741429 0.39072861 0.82874841]
 [0.28519562 0.35588211 0.         0.35502741 0.93254896 0.47513025
  0.30982887 0.87715481 0.61024943 0.54927687]
 [0.59342101 0.7073221  0.35502741 0.         0.90208081 0.12860637
  0.55640024 0.84480911 0.88591733 0.34157114]
 [1.18873526 1.02351632 0.93254896 0.90208081 0.         0.87073212
  0.72047948 0.05767583 0.79216284 0.59387424]
 [0.72166297 0.82106444 0.47513025 0.12860637 0.87073212 0.
  0.63872493 0.81505832 0.96456628 0.28027185]
 [0.49033107 0.3102678  0.30982887 0.55640024 0.72047948 0.63872493
  0.         0.67198344 0.32955437 0.56336543]
 [1.13566133 0.97741429 0.87715481 0.84480911 0.05767583 0.81505832
  0.67198344 0.         0.7614934  0.53935436]
 [0.6869617  0.39072861 0.61024943 0.88591733 0.79216284 0.96456628
  0.32955437 0.76149

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-24-8b2485b5e9f4>:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.37274387 -0.28267339 -0.09775775 -0.06355305  0.28269209  0.14443624
  -0.31246029  0.03773902  0.06944611 -0.15061285]
 [-0.29507502 -0.00458408 -0.08552895  0.39096903 -0.18910961  0.29900218
   0.11555248 -0.00656663  0.07512064 -0.29978004]
 [-0.33927382 -0.04551883  0.38059283 -0.08129869 -0.07044064  0.17531734
   0.46599168 -0.02949486 -0.19570092 -0.26017409]
 [-0.18345801 -0.20174131  0.27809716 -0.37296004  0.42126262  0.22595629
   0.34696951 -0.3757124  -0.28212467  0.14371087]
 [-0.03483415  0.13981322 -0.28675888  0.31024206  0.30535317  0.15419873
  -0.26473129 -0.30521986 -0.32520393  0.30714093]]


#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[0 0 1]
 [2 8 7]
 [2 8 5]]
[[0 0 1]
 [2 8 7]
 [2 8 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4913326502503793


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 4. 3. 4. 2. 1. 4. 2. 4. 4.]
[3. 7. 5. 7. 3. 1. 7. 3. 7. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first.
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[38 68 44 64]
 [57 43 56 67]
 [34 51 53 35]]
[[38 68 44 64]
 [57 43 56 67]
 [34 51 53 35]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.61421706 0.4165112  0.53159421 0.51151866 0.38034008 0.51176932
 0.38731998 0.69447225 0.54167176 0.52023989]
0    0.614217
1    0.416511
2    0.531594
3    0.511519
4    0.380340
5    0.511769
6    0.387320
7    0.694472
8    0.541672
9    0.520240
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([2.71142704, 1.20940853, 0.86643987, 0.86365033, 1.19695382])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 33) ( 3, 42) ( 5, 40) ( 5, 63) (12, 68) (12, 87) (14, 52) (14, 82)
 (26, 64) (26, 65) (30, 43) (30, 54) (30, 55) (30, 90) (32, 88) (32, 96)
 (33, 42) (36, 52) (36, 74) (40, 63) (43, 90) (45, 56) (45, 88) (52, 74)
 (52, 82) (54, 55) (56, 88) (64, 65) (68, 87) (88, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.56182626,  0.66517648,  0.1559677 ,  0.98180571, -0.50026833,
        0.95367797, -0.34176545, -0.01448903, -0.91656821, -0.25603807,
       -0.21618324,  0.90404395, -0.26401523,  0.30922029,  0.01133512,
        0.9389559 ,  0.44890196,  0.7818372 ,  0.82483606, -0.39020494,
        0.87205222,  0.93361059, -0.86640735, -0.41173022,  0.64086985,
       -0.46272586,  0.19896789, -0.84618172, -0.74531214,  0.8600289 ,
       -0.47874961,  0.96873404,  0.17611552, -0.37217947,  0.1946695 ,
       -0.10878204,  0.27432019, -0.91984339, -0.65183146,  0.37958609,
       -0.69968126, -0.75637525,  0.61482456,  0.26582159,  0.65915867,
       -0.55170231, -0.18636016, -0.25183566, -0.57717161,  0.99109859,
       -0.99809082,  0.26123432, -0.22048215, -0.69094426,  0.56552842,
        0.33078307, -0.43917921,  0.77645711,  0.79069159, -0.06161617,
       -0.23379227,  0.13657401,  0.68498713, -0.21126853,  0.52757373,
        0.25077698,  0.09916207, -0.84569892,  0.32880119, -0.45

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[12.23331348  4.70528714  4.20291154  3.4751867   2.07945314  8.77684008
  5.51360455  5.18045798  4.58994631  2.24861682]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.50037858  2.8693061   5.73562726  7.25449948  0.19505172 11.95966012
   2.1400445  12.41111131  6.12514901  3.87119305]
 [ 0.54461381  1.84736349  3.62088952  8.31647572  4.78091416  7.12104681
   0.65371225 12.36783673  6.55254095  0.16912778]
 [ 8.15928637  3.31169665 11.71336051  1.222917    0.35515017 13.7371371
   1.55507162  6.64471986  0.2082544   8.53687373]
 [ 6.42365582  1.63383671 10.5603905   2.01196776  1.94555713 11.92412728
   2.27453806  7.02940107  0.76773969  6.80240503]
 [ 1.95043379 11.72723817  8.7351761   0.74501366 15.36146927  0.82841113
  13.04047976  2.74797837  2.25706305  1.55325421]
 [ 3.63940905  3.37857882  0.52831001 11.13081377  6.02394604  4.99918702
   0.08675187 14.75612113  9.13790065  3.26540852]
 [ 8.40638323  4.94481317  4.79765112 16.22926977  7.07454493  2.33348887
   2.3249218  19.35833625 13.98149749  8.03660057]
 [ 6.35899584  9.98860984  1.54742437  8.53118436 12.85739988  0.869572
   6.55546387 10.71888466  5.68697079  5.97347917]
 [ 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

IndexError: ignored

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 4 2]
   [3 1 0]
   [3 4 4]]

  [[4 2 2]
   [1 0 0]
   [4 4 0]]

  [[2 2 3]
   [0 0 0]
   [4 0 3]]

  [[2 3 3]
   [0 0 1]
   [0 3 1]]

  [[3 3 0]
   [0 1 4]
   [3 1 1]]

  [[3 0 4]
   [1 4 4]
   [1 1 0]]

  [[0 4 2]
   [4 4 4]
   [1 0 0]]

  [[4 2 2]
   [4 4 4]
   [0 0 4]]]


 [[[3 1 0]
   [3 4 4]
   [1 4 4]]

  [[1 0 0]
   [4 4 0]
   [4 4 0]]

  [[0 0 0]
   [4 0 3]
   [4 0 3]]

  [[0 0 1]
   [0 3 1]
   [0 3 0]]

  [[0 1 4]
   [3 1 1]
   [3 0 4]]

  [[1 4 4]
   [1 1 0]
   [0 4 4]]

  [[4 4 4]
   [1 0 0]
   [4 4 2]]

  [[4 4 4]
   [0 0 4]
   [4 2 2]]]


 [[[3 4 4]
   [1 4 4]
   [1 1 4]]

  [[4 4 0]
   [4 4 0]
   [1 4 4]]

  [[4 0 3]
   [4 0 3]
   [4 4 0]]

  [[0 3 1]
   [0 3 0]
   [4 0 0]]

  [[3 1 1]
   [3 0 4]
   [0 0 3]]

  [[1 1 0]
   [0 4 4]
   [0 3 1]]

  [[1 0 0]
   [4 4 2]
   [3 1 1]]

  [[0 0 4]
   [4 2 2]
   [1 1 2]]]


 [[[1 4 4]
   [1 1 4]
   [4 1 0]]

  [[4 4 0]
   [1 4 4]
   [1 0 2]]

  [[4 0 3]
   [4 4 0]
   [0 2 3]]

  [[0 3 0]
   [4 0 0]
   [2 3 0]]

  [[3 0 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 7 16  8  7  5]
 [16  7  3  5 11]
 [ 8  3  7 42  7]
 [ 7  5 42  1  4]
 [ 5 11  7  4  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9996 9997 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
A = np.random.randint(0,5,(10,3))
print(A)
E = np.all(A[:,1:] == A[:,:-1], axis=1)
U = A[~E]
print(U)
U = A[A.max(axis=1) != A.min(axis=1),:]
print(U)

[[2 2 3]
 [1 1 2]
 [0 1 2]
 [3 2 1]
 [2 4 1]
 [3 0 4]
 [0 4 1]
 [1 0 0]
 [3 3 4]
 [4 4 0]]
[[2 2 3]
 [1 1 2]
 [0 1 2]
 [3 2 1]
 [2 4 1]
 [3 0 4]
 [0 4 1]
 [1 0 0]
 [3 3 4]
 [4 4 0]]
[[2 2 3]
 [1 1 2]
 [0 1 2]
 [3 2 1]
 [2 4 1]
 [3 0 4]
 [0 4 1]
 [1 0 0]
 [3 3 4]
 [4 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)
np.einsum('i,i->i', A, B)
np.einsum('i,i', A, B)
np.einsum('i,j->ij', A, B)

array([[0.642277  , 0.11923911, 0.3981756 , 0.16944887, 0.59595354,
        0.54030716, 0.02609672, 0.02149368, 0.57758282, 0.49989255],
       [0.02769683, 0.00514193, 0.01717048, 0.00730712, 0.02569923,
        0.0232996 , 0.00112537, 0.00092687, 0.02490703, 0.02155681],
       [0.24143206, 0.04482201, 0.14967429, 0.06369587, 0.22401906,
        0.20310158, 0.00980976, 0.00807948, 0.2171135 , 0.18790972],
       [0.66657122, 0.12374935, 0.41323665, 0.1758583 , 0.61849556,
        0.56074436, 0.02708383, 0.02230668, 0.59942997, 0.51880106],
       [0.13012989, 0.02415869, 0.08067321, 0.03433155, 0.12074443,
        0.10947008, 0.00528738, 0.00435477, 0.11702239, 0.10128179],
       [0.57151998, 0.10610303, 0.35431023, 0.15078138, 0.53029978,
        0.48078374, 0.02322175, 0.01912581, 0.51395289, 0.44482144],
       [0.62518242, 0.11606549, 0.38757792, 0.16493889, 0.58009188,
        0.52592657, 0.02540214, 0.02092161, 0.56221011, 0.48658762],
       [0.53284797, 0.09892355, 0.3303357

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.00222431  0.34614531]
